# 1.**A very simple neural network with nn module**

In [1]:
import torch
import torch.nn as nn

In [ ]:
# Create model class

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__() # always call parent constructor (nn.Module) first

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [3]:
# create dataset
x = torch.rand(10,5)

# create model
model = Model(x.shape[1])

# call model for forward pass
model(x)  # this will automaticall call "forward()" method of class Model. PyTorch override __call__() method to procceed that

tensor([[0.6148],
        [0.6584],
        [0.6078],
        [0.5962],
        [0.6387],
        [0.6145],
        [0.5424],
        [0.5872],
        [0.5600],
        [0.6377]], grad_fn=<SigmoidBackward0>)

In [5]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.2559,  0.0132,  0.3577, -0.3815, -0.1671]], requires_grad=True)

In [6]:
# show model bias
model.linear.bias

Parameter containing:
tensor([0.4101], requires_grad=True)

In [7]:
# to visualize whole network
!pip install torchinfo

In [8]:
from torchinfo import summary

summary(model, input_size=(x.shape))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# 2. **Simple Neural Network with a hidden layer**

In [3]:
# create model class

class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__() # always call parent constructor (nn.Module) first

    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [4]:
# create dataset
x = torch.rand(10,5)

# create model
model = Model(x.shape[1])

# call model for forward pass
model(x)

tensor([[0.4216],
        [0.4101],
        [0.4144],
        [0.4129],
        [0.4027],
        [0.4127],
        [0.4183],
        [0.4088],
        [0.4159],
        [0.4103]], grad_fn=<SigmoidBackward0>)

In [8]:
# show model weights
model.linear1.weight
model.linear2.weight

Parameter containing:
tensor([[ 0.1982,  0.0367, -0.4901]], requires_grad=True)

In [10]:
# show model bias
model.linear1.bias
model.linear2.bias

Parameter containing:
tensor([-0.3742], requires_grad=True)

In [12]:
from torchinfo import summary

summary(model, input_size=(x.shape))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# 3. **Simple Neural Network with Sequential Container**

In [13]:
# create model class

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__() # always call parent constructor (nn.Module) first

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
      )

  def forward(self, features):
    out = self.network(features)
    return out

In [14]:
# create dataset
x = torch.rand(10,5)

# create model
model = Model(x.shape[1])

# call model for forward pass
model(x)

tensor([[0.4798],
        [0.4770],
        [0.4496],
        [0.4493],
        [0.4654],
        [0.4356],
        [0.4802],
        [0.4688],
        [0.4661],
        [0.4575]], grad_fn=<SigmoidBackward0>)

In [19]:
# visualize whole network
summary(model, input_size=(x.shape))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# 4. **Creating training Pipeline in PyTorch with nn.Module**

In [69]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [70]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [71]:
df.shape

(569, 33)

In [72]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [73]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [74]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[: , 1:], df.iloc[: , 0], test_size=0.2)

In [75]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [76]:
X_train

array([[-1.00748541, -0.97259622, -1.02902109, ..., -1.74321571,
        -0.30851164, -1.32014489],
       [ 1.85435225,  2.77637574,  1.78126287, ...,  0.76580877,
        -0.03878063, -0.06194536],
       [-0.32826078,  0.00396755, -0.40607001, ..., -1.57519123,
        -0.77115154, -1.24357481],
       ...,
       [-0.87391404, -0.62751239, -0.9062437 , ..., -1.13161264,
        -0.86675241, -0.75720167],
       [-0.65792629, -0.22139332, -0.62402049, ..., -0.02213683,
         0.8643061 ,  0.02810105],
       [-0.2202669 ,  0.07908784, -0.27299249, ...,  0.01113534,
        -0.0114661 , -0.58078421]])

In [77]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [78]:
y_train

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,

In [99]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [100]:
X_train_tensor.shape

torch.Size([455, 30])

In [101]:
y_train_tensor.shape

torch.Size([455])

**Defining the model**

In [111]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__() # always all the parent constructor first

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  # not required to define loss_function when built-in PyTorch loss function is in use.
  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # calculate loss
    loss = -(y * torch.log(y_pred) + (1-y) * torch.log(1-y_pred)).mean()
    return loss

**Important parameters**

In [112]:
learning_rate = 0.1
epochs = 25

**PyToch built-in loss function to calculation loss**

In [113]:
loss_function = nn.BCELoss()

**Training pipeline**

In [114]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# PyTorch optimizer to calculate gradient
# define optimizer
# here: model.parameters() is a PyTorch method that retrieves an iterator over all the trainable parameters (weights, baises)
optimizer = torch.optim.SGD(model.parameters(), lr= learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  #loss calculate
  # manual way to calculate
  #loss = model.loss_function(y_pred, y_train_tensor)

  # from PyTroch built-in loss function
  loss = loss_function(y_pred, y_train_tensor.reshape(-1, 1))

  #clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  # manual to update
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad

  # from PyTorch built-in way to update
  optimizer.step()

  # zero gradients
  # manual to zero grad
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  # from built-in Pytorch way to zero grad (best to use before backword() method)
  # optimizer.zero_grad()

  # print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.8664147257804871
Epoch: 2, Loss: 0.600482165813446
Epoch: 3, Loss: 0.47037631273269653
Epoch: 4, Loss: 0.3996000289916992
Epoch: 5, Loss: 0.35489121079444885
Epoch: 6, Loss: 0.32360297441482544
Epoch: 7, Loss: 0.30016815662384033
Epoch: 8, Loss: 0.28176483511924744
Epoch: 9, Loss: 0.26680421829223633
Epoch: 10, Loss: 0.25431936979293823
Epoch: 11, Loss: 0.24368557333946228
Epoch: 12, Loss: 0.2344796359539032
Epoch: 13, Loss: 0.22640372812747955
Epoch: 14, Loss: 0.21924135088920593
Epoch: 15, Loss: 0.21283096075057983
Epoch: 16, Loss: 0.20704908668994904
Epoch: 17, Loss: 0.20179952681064606
Epoch: 18, Loss: 0.19700586795806885
Epoch: 19, Loss: 0.19260665774345398
Epoch: 20, Loss: 0.1885516494512558
Epoch: 21, Loss: 0.1847992092370987
Epoch: 22, Loss: 0.1813145875930786
Epoch: 23, Loss: 0.17806841433048248
Epoch: 24, Loss: 0.17503570020198822
Epoch: 25, Loss: 0.17219491302967072


In [115]:
model.linear.weight

Parameter containing:
tensor([[ 1.5320e-01,  2.3375e-01,  1.0122e-01,  4.2006e-01,  5.7270e-02,
          3.7220e-04,  1.6969e-01,  3.1353e-01, -2.5229e-02,  6.8731e-04,
          1.5958e-01, -1.7786e-01,  1.4773e-01,  1.4949e-01,  7.2109e-02,
         -3.1210e-02,  2.5833e-02,  6.6623e-02, -4.6427e-02, -3.0996e-02,
          3.5033e-01,  2.9758e-01,  2.3353e-01,  3.6843e-01,  1.8996e-01,
          1.8716e-02,  2.8713e-01,  2.4007e-01,  1.7629e-01,  4.8257e-02]],
       requires_grad=True)

In [116]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.549861490726471
