In [25]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [26]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [27]:
df.shape

(569, 33)

In [28]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [29]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

**Train Test Split**

In [30]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[: , 1:], df.iloc[: , 0], test_size=0.2)

**Scaling**

In [31]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [32]:
X_train

array([[-0.37049692,  2.19015673, -0.40486948, ..., -0.75072548,
        -0.82851882, -0.60254301],
       [ 1.43513766, -0.16963653,  1.37428792, ...,  1.48045751,
         0.98859786, -0.01557848],
       [-0.72420732, -0.22435637, -0.70815375, ...,  0.12939782,
        -0.15158437,  0.43245623],
       ...,
       [-1.55314478, -0.5640754 , -1.53153124, ..., -1.75558579,
        -0.71465657,  0.30301158],
       [-0.78410989, -0.89467446, -0.79545659, ..., -0.44383529,
        -0.35435275, -0.86868567],
       [-0.0938041 ,  0.0652028 , -0.14916732, ..., -0.8440461 ,
        -0.60859311, -0.78722482]])

In [33]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [34]:
y_train

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,

In [35]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [36]:
X_train_tensor.shape

torch.Size([455, 30])

In [37]:
y_train_tensor.shape

torch.Size([455])

**Defining Model**

In [42]:
class MySimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)


  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred


  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # calculate loss
    loss = -(y * torch.log(y_pred) + (1-y) * torch.log(1-y_pred)).mean()
    return loss


**Important Parameters**

In [39]:
learning_rate = 0.1
epochs = 25

**Training pipeline**

In [47]:
# create model
model = MySimpleNN(X_train_tensor)

#define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculation
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.757159055544816
Epoch: 2, Loss: 3.6483586040172655
Epoch: 3, Loss: 3.5323116165115596
Epoch: 4, Loss: 3.4144440367408495
Epoch: 5, Loss: 3.29192055871335
Epoch: 6, Loss: 3.1640659635247523
Epoch: 7, Loss: 3.032269832340871
Epoch: 8, Loss: 2.899850243347832
Epoch: 9, Loss: 2.7631818669836
Epoch: 10, Loss: 2.6211830377465426
Epoch: 11, Loss: 2.480564187500196
Epoch: 12, Loss: 2.333371971311768
Epoch: 13, Loss: 2.1792846021978973
Epoch: 14, Loss: 2.0278242702182485
Epoch: 15, Loss: 1.8787509859312415
Epoch: 16, Loss: 1.736157020749436
Epoch: 17, Loss: 1.5982033578658408
Epoch: 18, Loss: 1.4666856427440598
Epoch: 19, Loss: 1.3437118461108395
Epoch: 20, Loss: 1.2315879306414863
Epoch: 21, Loss: 1.1349284387423346
Epoch: 22, Loss: 1.0540677555862343
Epoch: 23, Loss: 0.9884686822301297
Epoch: 24, Loss: 0.9367387990542969
Epoch: 25, Loss: 0.8968418423732962


In [48]:
print(model.weights)
print(model.bias)

tensor([[-1.0138e-01],
        [ 2.8330e-01],
        [-2.2104e-01],
        [ 4.6644e-01],
        [-4.7699e-02],
        [-2.7473e-01],
        [-1.8874e-01],
        [ 2.6138e-01],
        [-2.8317e-01],
        [ 1.3364e-01],
        [ 3.3377e-02],
        [ 2.8457e-01],
        [-3.3352e-02],
        [ 3.1973e-01],
        [ 5.8174e-01],
        [ 3.8988e-01],
        [ 2.5915e-01],
        [-2.7294e-01],
        [ 3.5554e-01],
        [-3.3482e-04],
        [-1.9478e-02],
        [ 1.3239e-01],
        [ 3.8213e-01],
        [ 2.0053e-01],
        [ 1.6982e-01],
        [ 1.0482e-02],
        [-5.1023e-01],
        [-4.5521e-01],
        [ 3.2963e-01],
        [ 3.5628e-01]], dtype=torch.float64, requires_grad=True)
tensor([-0.1414], dtype=torch.float64, requires_grad=True)


**Evaluation**

In [49]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5147737860679626
